<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producer extends Model
{
    //
    protected $table='producer';
    public static function getProducerNameById($id){
        $name = Producer::where('id',$id)->value('name');
        return $name;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleted(function($model){
            $has = Productline::where('producer_id', $model->id)->exists();
            if($has){
                throw new \Exception('请先清空厂家下的产品线再来操作!');
            }
        });
    }
}
